### ISSUE TITLE
fix download errors in sandbox

### ISSUE THREAD

**Issue by awscott** [DigitalWPI/digitalwpi#101]
E-project-121418-075233 when looking at project, scrolling down and clicking action->download gives error, why?

**Comment by awscott** [comment]
need to update this for bob doing demos

**Comment by jayanthdeejay** [comment]
It probably is one of those problem PIDs that the application minted, which I have deleted as per the instructions on the LDP::Conflict issue.

**Comment by jayanthdeejay** [comment]
LDP::Conflict issue is resolved
