### ISSUE TITLE
Batch-Uploader: Embargos

### ISSUE THREAD

**Issue by awscott** [DigitalWPI/digitalwpi#106]
Implement some way to handle embargod / restricted works in batch. there is already code in the rake task that handles this in some way, but we need to understand it better and implement specific restrictions and embargoes

**Comment by jayanthdeejay** [comment]
https://github.com/samvera/hyrax/blob/2dfd7c427bbf258adeb5a34abd959f8ea1a1b20c/lib/generators/hyrax/templates/db/seeds.rb#L231-L266
