### ISSUE TITLE
get info from TC

### ISSUE THREAD

**Issue by awscott** [DigitalWPI/digitalwpi#143]
ask iam for the folloring stuff
app id - for their identity server
idp

**Comment by jayanthdeejay** [comment]
Contacted Cynthia and Thomas for on boarding our application. We probably should meet with Cynthia sometime this week.

**Comment by jayanthdeejay** [comment]
We did and have submitted the application on-boarding on Mar 6. Still waiting to hear from them.

**Comment by jayanthdeejay** [comment]
[Botelho-Filho, Antonino D](mailto:adbotelhofilho@wpi.edu) reached out to me regarding this and he needs the test environment for him to test SSO from his end.

**Comment by jayanthdeejay** [comment]
SSO code has been merged #181 #188
