### ISSUE TITLE
corrupt PDF strategy

### ISSUE THREAD

**Issue by awscott** [DigitalWPI/digitalwpi#144]
find a way to with the messed up pdfs

**Comment by jayanthdeejay** [comment]
Used [this](https://superuser.com/questions/278562/how-can-i-fix-repair-a-corrupted-pdf-file) to try and fix one of the corrupted PDFs. 

```shell
GPL Ghostscript 9.02 (2011-03-30)
Copyright (C) 2010 Artifex Software, Inc.  All rights reserved.
This software comes with NO WARRANTY: see the file PUBLIC for details.
   **** Warning: File has a corrupted %%EOF marker, or garbage after %%EOF.
   **** Warning:  An error occurred while reading an XREF table.
   **** The file has been damaged.  This may have been caused
   **** by a problem while converting or transfering the file.
   **** Ghostscript will attempt to recover the data.
   **** Error:  Trailer is not found.
Error: /stackunderflow in --run--
```
Attached the corrupt file to this comment.
[99D248M.pdf](https://github.com/DigitalWPI/digitalwpi/files/2902495/99D248M.pdf)

**Comment by jayanthdeejay** [comment]
We have already fixed GhostScript issues by dialing down the version from latest to 9.07. There aren't very many options here. @aneslin Could you please weigh in on this?
