### ISSUE TITLE
facet items 

### ISSUE THREAD

**Issue by awscott** [DigitalWPI/digitalwpi#174]
things to facet by:
advisor, contributor, sponsor, date, project center, geo location / based near, language, publisher, degree, "unit", collection, resource type, subject. 

![uploads/33e1c5af-d7cc-4b3d-91bc-71f0d02dd132/facet_items_april1.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F33e1c5af-d7cc-4b3d-91bc-71f0d02dd132%2Ffacet_items_april1.jpg)

**Comment by jayanthdeejay** [comment]
#189 fixes this
