### ISSUE TITLE
finish setting up QA servers

### ISSUE THREAD

**Issue by awscott** [DigitalWPI/digitalwpi#22]
set up hyrax-qa.wpi.edu and data-qa.wpi.edu servers and get things running, using ansible
blocks #23 
blocks #24

**Comment by awscott** [comment]
im having a lot a trouble with this, im terrible at dev ops. but I talked to James today and now have access to the "VM Portal" so now I should be able to reset the machines, and manage them. meaning I can experiment more with ansible

**Comment by jayanthdeejay** [comment]
I'm closing this issue. We can re-open if need be.
