### ISSUE TITLE
Collection type translation missing

### ISSUE THREAD

**Issue by jayanthdeejay** [DigitalWPI/digitalwpi#227]
https://github.com/samvera/hyrax/issues/3136
https://github.com/curationexperts/laevigata/pull/1250

<img width="1389" alt="Screen Shot 2019-05-29 at 12 19 16 PM" src="https://user-images.githubusercontent.com/2188493/58573729-53e13f80-820c-11e9-9d3a-62b9480b71a9.png">

**Comment by jayanthdeejay** [comment]
Fixed this from the console.

**Comment by scherztc** [comment]
@jayanthdeejay I am dealing with this in my test suite when I am upgrading to 2.5.1.  Any tips on how to deal with this in a test suite?

**Comment by jayanthdeejay** [comment]
@scherztc ran [this](https://github.com/curationexperts/laevigata/pull/1250/files) rake task. Not a permanent fix but does the job.

**Comment by scherztc** [comment]
@jayanthdeejay Did you have to add env=test to the rake task?

**Comment by jayanthdeejay** [comment]
We encountered this issue only on our production instance (though, our test instance is also running on prod mode and closely replicates our prod) and I manually ran the rake task commands to replace the missing text from console rather than running the task itself.
