### ISSUE TITLE
update team member in about page

### ISSUE THREAD

**Issue by zchen12wpi** [DigitalWPI/digitalwpi#281]
move Bob's information from current contributors to Previous contributors, add Andy's information in current contributors.
/views/static/about-page.html.erb
add contact email in /views/shared/_footer.html.erb

**Comment by jayanthdeejay** [comment]
Bob left the project??

**Comment by zchen12wpi** [comment]
Hi Jay,

Bob retired in June. In WPI 57 employee took the good retired package.
How are you? Jay. Are you in CA now?

-Jimmy


Zhimin (Jimmy) Chen

George C. Gordon Library
Librarian for Core Systems and Digital Repository Administration


Worcester Polytechnic Institute
100 Institute Road, Worcester, MA  01609
508-831-6231 (O)
zchen12@wpi.edu
wpi.edu/library


________________________________

**Comment by jayanthdeejay** [comment]
I've moved to India for good.

**Comment by zchen12wpi** [comment]
It's great, live with family and friends should better for you.
Keep in touch.


Zhimin (Jimmy) Chen

George C. Gordon Library
Librarian for Core Systems and Digital Repository Administration


Worcester Polytechnic Institute
100 Institute Road, Worcester, MA  01609
508-831-6231 (O)
zchen12@wpi.edu
wpi.edu/library


________________________________
