### ISSUE TITLE
Spotlight: Go Live with beta, update links, remove redirect

### ISSUE THREAD

**Issue by emilyobvs** [DigitalWPI/digitalwpi#415]
Currently exhibits.wpi.edu redirects to the Digital WPI homepage. ASC should be ready to go-live with exhibits at the end of the summer and anticipates the week before AY 2023 starts as removal date for redirect.

**Comment by emilyobvs** [comment]
Archives will discuss whether they will wait for the Higgins exhibit before go-live

**Comment by emilyobvs** [comment]
Beta logo, label, or note should be added to exhibits.wpi.edu to indicate it is a beta site. Derek confirmed adding it to the logo shouldn't be a problem. He will work on this before removing the redirect.

Also before removing the redirect, the links in Hyrax Collections page will need to be updated (https://digital.wpi.edu/col):

- Under "Exhibits", Theo Brown Diaries should be removed
- Add the following: 

1. "Digital Exhibits Homepage", link to https://exhibits.wpi.edu/
2. "Featured Exhibit: A Life Unfolded: The Duane D. Pearsall papers", link to https://exhibits.wpi.edu/spotlight/pearsall
3. "Featured Exhibit: Illustrating Dickens' World", link to https://exhibits.wpi.edu/spotlight/illustrating-dickens
4. "Featured Exhibit: Reflections of Tony", link to https://exhibits.wpi.edu/spotlight/tony-king

**Comment by emilyobvs** [comment]
Updated Browse By dropdown with "Browse Exhibits"

**Comment by emilyobvs** [comment]
ETA Tuesday, 11/28 to go-live

**Comment by emilyobvs** [comment]
exhibits.wpi.edu beta version is now public!

Updating list of to do items here:

- [ ] Links in Hyrax Collections page need to be updated (https://digital.wpi.edu/col). Under "Exhibits", Theo Brown Diaries should be removed and the following added:
"Digital Exhibits Homepage", link to https://exhibits.wpi.edu/
"Featured Exhibit: A Life Unfolded: The Duane D. Pearsall papers", link to https://exhibits.wpi.edu/spotlight/pearsall
"Featured Exhibit: Illustrating Dickens' World", link to https://exhibits.wpi.edu/spotlight/illustrating-dickens
"Featured Exhibit: Reflections of Tony", link to https://exhibits.wpi.edu/spotlight/tony-king
- [ ] Update Browse By dropdown with "Browse Exhibits" and link to exhibits.wpi.edu

**Comment by dfmurphy-wpi** [comment]
Exhibits has been made public. Redirect has been removed and links on Digital have been updated.
