### ISSUE TITLE
UX: Messaging on embargoed and WPI only works

### ISSUE THREAD

**Issue by emilyobvs** [DigitalWPI/digitalwpi#421]
Add custom message and login link from browser viewer for embargoed or WPI only works, right now it shows “Unexpected server response” for users that are not logged in – DM – expects to make progress soon. Download behavior: Customize display on browse collections based on login. Add notes where relevant to clarify that login is required for some things. Create login screen? Like: https://www.digitalcommonwealth.org/users/sign_in - DM will work beginning soon

**Comment by emilyobvs** [comment]
Examples of changes: https://wpi0.sharepoint.com/:p:/s/gr-hyrax-wg/EVTXjp12WjJKr52tmYqVmc8BtFxPrp1FOyjbhhItjxNiiQ?e=18YcMC. Additional documents on examples from other institutions, etc. located in the onedrive folder: https://wpi0.sharepoint.com/:f:/s/gr-hyrax-wg/EmEX4SBoMaVMlizqz78Luk0BaiQlt2sZxvgTl4l7gycwmQ?e=8DvBlr.

**Comment by emilyobvs** [comment]
Derek will deploy to test environment, Emily and Lori will test and decide if it should be deployed to prod.

**Comment by emilyobvs** [comment]
Checked test environment for embargoed works and confirmed the pdf link is not available for embargoed works. Other records without embargoed works still show the link and looks good.

Keeping this issue open for other aspects of this request, but we can create new issues for each of these if that helps:

- Add custom message and login link from browser viewer for WPI only works, right now it shows “Unexpected server response” for users that are not logged in
- Add notes where relevant to clarify that login is required for some things. Create login screen? Like: https://www.digitalcommonwealth.org/users/sign_in

**Comment by emilyobvs** [comment]
Derek updated the views for public vs logged in users and the following were tested successfully:

- if the file is public, public user can open in viewer.
- if you try to access a non-public file while not logged in, it sends you to the login page with a note saying you’re not authorized to access that file.
- if you are logged in and access a WPI only file, you can open in viewer
- if you are logged in and try to access a restricted file, it should take you back to the work page and say you don’t have access.
- admins can view all

**Comment by emilyobvs** [comment]
Ready to deploy to prod

**Comment by annakgold** [comment]
One more thing: we want to get rid of the word "private" but distinguish between "Embargoed" for totally embargoed works and "WPI" or "WPI only" for restricted to WPI access. Derek thinks it's a quick change (language or template).  Same language is used in Archives.

**Comment by emilyobvs** [comment]
There is a separate issue for changing the WPI Only label = #462 . Checking with team before Derek moves forward with deploying the changes mentioned in this issue.

**Comment by dfmurphy-wpi** [comment]
This change has been deployed to Prod. Will continue label change work in Issue #462.
