### ISSUE TITLE
Content: Update project center names

### ISSUE THREAD

**Issue by emilyobvs** [DigitalWPI/digitalwpi#425]
Updates from eProjects are coming through now. Lori will compare to see if Browse by Collection is missing some. - summer project

**Comment by emilyobvs** [comment]
Derek is working on this, will be done soon

**Comment by emilyobvs** [comment]
Derek will add new project center names to the Browse Collections by the end of the month.

New issue will be created for any records that require multiple project center names/changes.

**Comment by dfmurphy-wpi** [comment]
Project Center list has been updated to match facets
