### ISSUE TITLE
Content: Remove NOTE from GPS Posters

### ISSUE THREAD

**Issue by emilyobvs** [DigitalWPI/digitalwpi#447]
The CDR note should be removed from all records in the GPS Posters Collection. "This report represents the work of one or more WPI undergraduate students submitted to the faculty as evidence of completion of a degree requirement. WPI routinely publishes these reports on its website without editorial or peer review." 

Collection: https://digital.wpi.edu/collections/gps

**Comment by dfmurphy-wpi** [comment]
This has been removed from all GPS Posters in Hyrax. Going forward, note should not be included in the GPS ingests.
