### ISSUE TITLE
System: Increase file limit

### ISSUE THREAD

**Issue by emilyobvs** [DigitalWPI/digitalwpi#478]
Derek was able to increase file limit from 512MB to 1GB, working in dev, needs to be deployed to prod

**Comment by emilyobvs** [comment]
NOTE: File size for eprojects increased to .5 GB

Derek will follow up with Ermal about youtube archival channel/account

**Comment by emilyobvs** [comment]
Derek needs to clear out cache file for javascript, will be part of deployment with SDG

**Comment by dfmurphy-wpi** [comment]
cache appears to be updated. limit is now 1GB.
