### ISSUE TITLE
Content: Remove All Rights Reserved from License

### ISSUE THREAD

**Issue by emilyobvs** [DigitalWPI/digitalwpi#514]
Derek will remove the "All Rights Reserved" license from all work types in Hyrax. ARR is not a license, and the link (https://www.europeana.eu/en/rights/rr-r) brings you to the europeana site that states that ARR has been retired.

When license field does not contain any values, it will not be displayed in the record.

**Comment by emilyobvs** [comment]
Derek is working on pulling the list of records now, and will let us know when this is complete.

**Comment by emilyobvs** [comment]
Derek has completed this in test and prod. He will remove "All Rights Reserved" from the list (set it to false) and remove the not-secure creative commons (http instead of https)

**Comment by emilyobvs** [comment]
Derek needs to disable options from the License field dropdown

**Comment by dfmurphy-wpi** [comment]
License is no longer active in controlled vocabulary. Deployed to Production.
