### ISSUE TITLE
UX: Discuss bookmark functionality

### ISSUE THREAD

**Issue by emilyobvs** [DigitalWPI/digitalwpi#523]
Anusha enabled the bookmark feature in the test environment. WG should discuss desired functionality that is not already available:

- Tagging/Bookmark folders - Paul and Anusha discussed a solution and the issue has already been added to the CL kanban: https://github.com/antleaf/wpi-repository-project/issues/114
- Select All from results to bookmark a list of records
- Determine location of Bookmarks link - In the User name dropdown?

**Comment by emilyobvs** [comment]
Related to Cottage Labs issue: https://github.com/antleaf/wpi-repository-project/issues/14

**Comment by emilyobvs** [comment]
Anusha is working on this.

**Comment by emilyobvs** [comment]
WG is reviewing the new changes Anusha made on 5/23 - https://wpi0.sharepoint.com/:w:/s/gr-hyrax-wg/EdNiLLcOosNJrUGpoucgDbsBrhRcIDVVlMHXv3vUgeMcow?e=M79GHd

Updates also provided in the CL issue https://github.com/antleaf/wpi-repository-project/issues/14

**Comment by emilyobvs** [comment]
This was completed by Anusha and live in the production env't.

**Comment by annakgold** [comment]
[like]  Gold, Anna reacted to your message:
________________________________
From: emilyobvs ***@***.***>
Sent: Thursday, September 5, 2024 4:00:53 PM
To: DigitalWPI/digitalwpi ***@***.***>
Cc: Gold, Anna ***@***.***>; Assign ***@***.***>
Subject: [EXT] Re: [DigitalWPI/digitalwpi] UX: Discuss bookmark functionality (Issue #523)


This was completed by Anusha and live in the production env't.
